export { builtin_abs } from './gen/abs'
export { builtin_concat } from './gen/concat'
export { builtin_dataType } from './gen/dataType'
export { builtin_getArg } from './gen/getArg'
export { builtin_getTime } from './gen/getTime'
export { builtin_makeList } from './gen/makeList'
export { builtin_makeString } from './gen/makeString'
export { builtin_max } from './gen/max'
export { builtin_min } from './gen/min'
export { builtin_randomize } from './gen/randomize'
export { builtin_sgn } from './gen/sgn'
export { builtin_toInteger } from './gen/toInteger'
export { builtin_toString } from './gen/toString'

export { builtin_tadsSay } from './io/tadsSay'