interface IOpcode {
  name: string;
  size: number;
}

export const OPCODES: IOpcode[] = [
  /* 0x00 */ null,
  /* 0x01 */ { name: 'PUSH_0', size: 0 },
  /* 0x02 */ { name: 'PUSH_1', size: 0 },
  /* 0x03 */ { name: 'PUSHINT8', size: 1 },
  /* 0x04 */ { name: 'PUSHINT', size: 4 },
  /* 0x05 */ { name: 'PUSHSTR', size: 4 },
  /* 0x06 */ { name: 'PUSHLST', size: 4 },
  /* 0x07 */ { name: 'PUSHOBJ', size: 4 },
  /* 0x08 */ { name: 'PUSHNIL', size: 0 },
  /* 0x09 */ { name: 'PUSHTRUE', size: 0 },
  /* 0x0A */ { name: 'PUSHPROPID', size: 2 },
  /* 0x0B */ { name: 'PUSHFNPTR', size: 4 },
  /* 0x0C */ { name: 'PUSHSTRI', size: 0 }, /* variable length */
  /* 0x0D */ { name: 'PUSHPARLST', size: 1 },
  /* 0x0E */ { name: 'MAKELSTPAR', size: 0 },
  /* 0x0F */ { name: 'PUSHENUM', size: 4 },
  /* 0x10 */ { name: 'PUSHBIFPTR', size: 4 },
  /* 0x11 */ null,
  /* 0x12 */ null,
  /* 0x13 */ null,
  /* 0x14 */ null,
  /* 0x15 */ null,
  /* 0x16 */ null,
  /* 0x17 */ null,
  /* 0x18 */ null,
  /* 0x19 */ null,
  /* 0x1A */ null,
  /* 0x1B */ null,
  /* 0x1C */ null,
  /* 0x1D */ null,
  /* 0x1E */ null,
  /* 0x1F */ null,
  /* 0x20 */ { name: 'NEG', size: 0 },
  /* 0x21 */ { name: 'BNOT', size: 0 },
  /* 0x22 */ { name: 'ADD', size: 0 },
  /* 0x23 */ { name: 'SUB', size: 0 },
  /* 0x24 */ { name: 'MUL', size: 0 },
  /* 0x25 */ { name: 'BAND', size: 0 },
  /* 0x26 */ { name: 'BOR', size: 0 },
  /* 0x27 */ { name: 'SHL', size: 0 },
  /* 0x28 */ { name: 'ASHR', size: 0 },
  /* 0x29 */ { name: 'XOR', size: 0 },
  /* 0x2A */ { name: 'DIV', size: 0 },
  /* 0x2B */ { name: 'MOD', size: 0 },
  /* 0x2C */ { name: 'NOT', size: 0 },  
  /* 0x2D */ { name: 'BOOLIZE', size: 0 },
  /* 0x2E */ { name: 'INC', size: 0 },
  /* 0x2F */ { name: 'DEC', size: 0 },
  /* 0x30 */ { name: 'LSHR', size: 0 },
  /* 0x31 */ null,
  /* 0x32 */ null,
  /* 0x33 */ null,
  /* 0x34 */ null,
  /* 0x35 */ null,
  /* 0x36 */ null,
  /* 0x37 */ null,
  /* 0x38 */ null,
  /* 0x39 */ null,
  /* 0x3a */ null,
  /* 0x3b */ null,
  /* 0x3c */ null,
  /* 0x3d */ null,
  /* 0x3e */ null,
  /* 0x3f */ null,
  /* 0x40 */ { name: 'EQ', size: 0 },
  /* 0x41 */ { name: 'NE', size: 0 },
  /* 0x42 */ { name: 'LT', size: 0 },
  /* 0x43 */ { name: 'LE', size: 0 },
  /* 0x44 */ { name: 'GT', size: 0 },
  /* 0x45 */ { name: 'GE', size: 0 },
  /* 0x46 */ null,
  /* 0x47 */ null,
  /* 0x48 */ null,
  /* 0x49 */ null,
  /* 0x4a */ null,
  /* 0x4b */ null,
  /* 0x4c */ null,
  /* 0x4d */ null,
  /* 0x4e */ null,
  /* 0x4f */ null,
  /* 0x50 */ { name: 'RETVAL', size: 0 },
  /* 0x51 */ { name: 'RETNIL', size: 0 },
  /* 0x52 */ { name: 'RETTRUE', size: 0 },
  /* 0x53 */ null,
  /* 0x54 */ { name: 'RET', size: 0 },
  /* 0x55 */ null,
  /* 0x56 */ { name: 'NAMEDARGPTR', size: 3 },
  /* 0x57 */ { name: 'NAMEDARGTAB', size: 0 }, /* variable size */
  /* 0x58 */ { name: 'CALL', size: 5 },
  /* 0x59 */ { name: 'PTRCALL', size: 1 },
  /* 0x5a */ null,
  /* 0x5b */ null,
  /* 0x5c */ null,
  /* 0x5d */ null,
  /* 0x5e */ null,
  /* 0x5f */ null,

  /* 0x60 */ { name: 'GETPROP', size: 2 },
  /* 0x61 */ { name: 'CALLPROP', size: 3 },
  /* 0x62 */ { name: 'PTRCALLPROP', size: 1 },
  /* 0x63 */ { name: 'GETPROPSELF', size: 2 },
  /* 0x64 */ { name: 'CALLPROPSELF', size: 3 },
  /* 0x65 */ { name: 'PTRCALLPROPSELF', size: 1 },
  /* 0x66 */ { name: 'OBJGETPROP', size: 6 },
  /* 0x67 */ { name: 'OBJCALLPROP', size: 7 },
  /* 0x68 */ { name: 'GETPROPDATA', size: 2 },
  /* 0x69 */ { name: 'PTRGETPROPDATA', size: 0 },
  /* 0x6a */ { name: 'GETPROPLCL1', size: 3 },
  /* 0x6b */ { name: 'CALLPROPLCL1', size: 4 },
  /* 0x6c */ { name: 'GETPROPR0', size: 2 },
  /* 0x6d */ { name: 'CALLPROPR0', size: 3 },
  /* 0x6e */ null,
  /* 0x6f */ null,
  /* 0x70 */ null,
  /* 0x71 */ null,
  /* 0x72 */ { name: 'INHERIT', size: 3 },
  /* 0x73 */ { name: 'PTRINHERIT', size: 1 },
  /* 0x74 */ { name: 'EXPINHERIT', size: 7 },
  /* 0x75 */ { name: 'PTREXPINHERIT', size: 5 },
  /* 0x76 */ { name: 'VARARGC', size: 0 },
  /* 0x77 */ { name: 'DELEGATE', size: 3 },
  /* 0x78 */ { name: 'PTRDELEGATE', size: 1 },
  /* 0x79 */ null,
  /* 0x7a */ { name: 'SWAP2', size: 0 },
  /* 0x7b */ { name: 'SWAPN', size: 2 },
  /* 0x7c */ { name: 'GETARGN0', size: 0 },
  /* 0x7d */ { name: 'GETARGN1', size: 0 },
  /* 0x7e */ { name: 'GETARGN2', size: 0 },
  /* 0x7f */ { name: 'GETARGN3', size: 0 },
  /* 0x80 */ { name: 'GETLCL1', size: 1 },
  /* 0x81 */ { name: 'GETLCL2', size: 2 },
  /* 0x82 */ { name: 'GETARG1', size: 1 },
  /* 0x83 */ { name: 'GETARG2', size: 2 },
  /* 0x84 */ { name: 'PUSHSELF', size: 0 },
  /* 0x85 */ { name: 'GETDBLCL', size: 4 },
  /* 0x86 */ { name: 'GETDBARG', size: 4 },
  /* 0x87 */ { name: 'GETARGC', size: 0 },
  /* 0x88 */ { name: 'DUP', size: 0 },
  /* 0x89 */ { name: 'DISC', size: 0 },
  /* 0x8a */ { name: 'DISC1', size: 1 },
  /* 0x8b */ { name: 'GETR0', size: 0 },
  /* 0x8c */ { name: 'GETDBARGC', size: 2 },
  /* 0x8d */ { name: 'SWAP', size: 0 },
  /* 0x8e */ { name: 'PUSHCTXELE', size: 1 },
  /* 0x8f */ { name: 'DUP2', size: 0 },
  /* 0x90 */ { name: 'SWITCH', size: 0 }, /* variable size */
  /* 0x91 */ { name: 'JMP', size: 2 },
  /* 0x92 */ { name: 'JT', size: 2 },
  /* 0x93 */ { name: 'JF', size: 2 },
  /* 0x94 */ { name: 'JE', size: 2 },
  /* 0x95 */ { name: 'JNE', size: 2 },
  /* 0x96 */ { name: 'JGT', size: 2 },
  /* 0x97 */ { name: 'JGE', size: 2 },
  /* 0x98 */ { name: 'JLT', size: 2 },
  /* 0x99 */ { name: 'JLE', size: 2 },
  /* 0x9a */ { name: 'JST', size: 2 },
  /* 0x9b */ { name: 'JSF', size: 2 },
  /* 0x9c */ { name: 'LJSR', size: 2 },
  /* 0x9d */ { name: 'LRET', size: 2 },
  /* 0x9e */ { name: 'JNIL', size: 2 },
  /* 0x9f */ { name: 'JNOTNIL', size: 2 },
  /* 0xa0 */ { name: 'JR0T', size: 2 },
  /* 0xa1 */ { name: 'JROF', size: 2 },
  /* 0xa2 */ { name: 'ITERNEXT', size: 3 },
  /* 0xa3 */ null,
  /* 0xa4 */ null,
  /* 0xa5 */ null,
  /* 0xa6 */ { name: 'GETSPN', size: 1 },
  /* 0xa7 */ null,
  /* 0xa8 */ null,
  /* 0xa9 */ null,
  /* 0xaa */ { name: 'GETLCLN0', size: 0 },
  /* 0xab */ { name: 'GETLCLN1', size: 0 },
  /* 0xac */ { name: 'GETLCLN2', size: 0 },
  /* 0xad */ { name: 'GETLCLN3', size: 0 },
  /* 0xae */ { name: 'GETLCLN4', size: 0 },
  /* 0xaf */ { name: 'GETLCLN5', size: 0 },
  /* 0xb0 */ { name: 'SAY', size: 4 },
  /* 0xb1 */ { name: 'BUILTIN_A', size: 2 },
  /* 0xb2 */ { name: 'BUILTIN_B', size: 2 },
  /* 0xb3 */ { name: 'BUILTIN_C', size: 2 },
  /* 0xb4 */ { name: 'BUILTIN_D', size: 2 },
  /* 0xb5 */ { name: 'BUILTIN1', size: 3 },
  /* 0xb6 */ { name: 'BUILTIN2', size: 4 },
  /* 0xb7 */ null,
  /* 0xb8 */ { name: 'THROW', size: 0 },
  /* 0xb9 */ { name: 'SAYVAL', size: 0 },
  /* 0xba */ { name: 'INDEX', size: 0 },
  /* 0xbb */ { name: 'IDXLCL1INT8', size: 2 },
  /* 0xbc */ { name: 'IDXINT8', size: 1 },
  /* 0xbd */ null,
  /* 0xbe */ null,
  /* 0xbf */ null,
  /* 0xc0 */ { name: 'NEW1', size: 2 },
  /* 0xc1 */ { name: 'NEW2', size: 4 },
  /* 0xc2 */ { name: 'TRNEW1', size: 2 },
  /* 0xc3 */ { name: 'TRNEW2', size: 4 },  
  /* 0xc4 */ null,
  /* 0xc5 */ null,
  /* 0xc6 */ null,
  /* 0xc7 */ null,
  /* 0xc8 */ null,
  /* 0xc9 */ null,
  /* 0xca */ null,
  /* 0xcb */ null,
  /* 0xcc */ null,
  /* 0xcd */ null,
  /* 0xce */ null,
  /* 0xcf */ null,
  /* 0xd0 */ { name: 'INCLCL', size: 2 },
  /* 0xd1 */ { name: 'DECLCL', size: 2 },
  /* 0xd2 */ { name: 'ADDILCL1', size: 2 },
  /* 0xd3 */ { name: 'ADDILCL4', size: 6 },
  /* 0xd4 */ { name: 'ADDTOLCL', size: 2 },
  /* 0xd5 */ { name: 'SUBFROMLCL', size: 2 },
  /* 0xd6 */ { name: 'ZEROLCL1', size: 1 },
  /* 0xd7 */ { name: 'ZEROLCL2', size: 2 },
  /* 0xd8 */ { name: 'NILLCL1', size: 1 },
  /* 0xd9 */ { name: 'NILLCL2', size: 2 },
  /* 0xda */ { name: 'ONELCL1', size: 1 },
  /* 0xdb */ { name: 'ONELCL2', size: 2 },
  /* 0xdc */ null,
  /* 0xdd */ null,
  /* 0xde */ null,
  /* 0xdf */ null,
  /* 0xe0 */ { name: 'SETLCL1', size: 1 },
  /* 0xe1 */ { name: 'SETLCL2', size: 2 },
  /* 0xe2 */ { name: 'SETARG1', size: 1 },
  /* 0xe3 */ { name: 'SETARG2', size: 2 },
  /* 0xe5 */ { name: 'SETPROP', size: 2 },
  /* 0xe4 */ { name: 'SETIND', size: 0 },
  /* 0xe6 */ { name: 'PTRSETPROP', size: 0 },
  /* 0xe7 */ { name: 'SETPROPSELF', size: 2 },
  /* 0xe8 */ { name: 'OBJSETPROP', size: 6 },
  /* 0xe9 */ { name: 'SETDBLCL', size: 4 },
  /* 0xea */ { name: 'SETDBARG', size: 4 },
  /* 0xeb */ { name: 'SETSELF', size: 0 },
  /* 0xec */ { name: 'LOADCTX', size: 0 },
  /* 0xed */ { name: 'STORECTX', size: 0 },
  /* 0xee */ { name: 'SETLCL1R0', size: 1 },
  /* 0xef */ { name: 'SETINDLCL1I8', size: 2 },
  /* 0xf0 */ null,
  /* 0xf1 */ { name: 'BP', size: 0 },
  /* 0xf2 */ { name: 'NOP', size: 0 }
]